### ISSUE TITLE
runtime check failure

### ISSUE THREAD

**Issue by murtraja** [kvakvs/hge#5]
I need to explicitly set 
#define HGE_DIRECTX_VER  9
in order for hge to not give me this error:

Run-Time Check Failure #0 - The value of ESP was not properly saved across a function call.  This is usually a result of calling a function declared with one calling convention with a function pointer declared with a different calling convention

at function call Texture_load (line 119 in tutorial2.cpp)

**Comment by kvakvs** [comment]
I probably should check if that symbol `HGE_DIRECTX_VER` is defined and default it to 9 with a warning. Makes sense.

**Comment by murtraja** [comment]
the latter
