### ISSUE TITLE
Client size calculation wrong on Windows 10

### ISSUE THREAD

**Issue by kvakvs** [kvakvs/hge#6]
On Windows 10 client size is calculated by ±10 pixels off.

Possible cause: Adjust call in system.cpp on window creation.

![image](https://user-images.githubusercontent.com/288724/46144176-76c1eb00-c25c-11e8-9900-677fb03d909a.png)

**Comment by kvakvs** [comment]
I have added WS_BORDER style to the frame size calculation, not sure how to test it but please re-download HGE or do `git pull` and then give it a try.

**Comment by erikhellstrom** [comment]
Cool! I can check earliest tonight. 

But will this retain compatability win win 7 and win xp? Should not the window styles be fetched from the actual window at startup?

**Comment by kvakvs** [comment]
I have added WS_BORDER style to the frame size calculation, not sure how to test it but please re-download HGE or do `git pull` and then give it a try.

**Comment by kvakvs** [comment]
Window styles are calculated according to selected mode, fullscreen or windowed, if windowed there's also header bar and closing buttons. And then window box is adjusted using the styles to include window decorations in size. This should be fairly compatible, if styles are set correctly (which needs checking).

**Comment by erikhellstrom** [comment]
Hi again! I get this error but not sure where to set this version:

`Error (active)	E0035	#error directive: Please set HGE_DIRECTX_VER to 8 or 9	supremacy	C:\Dropbox\PROJECT\code\hge181\include\hge.h	15`

I downloaded it all and replaced all includes and also replaced hge.dll in my project with the one from tutorials/precompiled (since this one was edited 20 hours ago I figured it was the new one).

**Comment by kvakvs** [comment]
Set it in CMakeLists.txt in the root of the project.
It has also default value 9.

**Comment by erikhellstrom** [comment]
I get past that now with some defines. But the new version doesnt have any "hge.lib" file, which is demanded for me to compile ("cannot open file 'hge.lib'). I havent any reference in my own code to that file. It used to be in the folder lib/vc.

Ps. Thank you for your help!

**Comment by kvakvs** [comment]
It is still same HGE that you downloaded before, this part did not change despite me changing a lot in the source. Follow the build instructions in README and then pick up output files in `linklib` and binaries in `bin`.

**Comment by erikhellstrom** [comment]
No SLN file is created by cMake. I get no errors in CMakeOutput.log but still no solutions file in the _build folder hierarchy.

It creates a CmakeFiles folder and inside that a 3.12.2 and CMakeTmp folder. But there is no solutions file to build. I use a directx 9 SDK which is assigned in the CMakeLists.txt.

**Comment by kvakvs** [comment]
For now my best suggestion would be to see your screen cast over a live Hangouts or Skype or Discord call. Or a remote control like TeamViewer.

**Comment by erikhellstrom** [comment]
Yeah I can do skype anytime during today before 16.30. Tonight I cannot im afraid. 
Skypename:
"salladskungen"

**Comment by erikhellstrom** [comment]
Hi again!
A new oddity I found is that it now creates the window with upper-left corner in the middle of the screen. Which means 3/4 of the window is outside your screen and needs to be dragged.

In the old version the window was created centered on the screen, fitting it on the screen if possible, which was better.

**Comment by kvakvs** [comment]
I will add the change to the source when i've got a minute, latest in a week.
Thanks!
